Import('g_env')

l_sources = []

for l_source in l_sources:
  g_env.sources.append( g_env.Object( l_source ) )

g_env.exe['bench_gemm'] = g_env.Object( 'bench_gemm.cpp' )

if g_env['tblis'] != False:
  g_env.exe['bench_tblis'] = g_env.Object( 'bench_tblis.cpp' )

Export('g_env')